language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.0"
  - "iojs"
before_script:
  - npm install -g gulp
  - npm install
  - npm install -g bower
  - bower install

script:
  - gulp tests
  - gulp bower