language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.0"
  - "iojs"
before_script:
  - npm install -g gulp
  - npm install
  - npm install -g bower
  - gulp init_test
  - gulp unit_test

script:
  - gulp sass
  - bower install

after_script:
  - gulp init_test
  - gulp unit_test